//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_NewsType
    {
        public A_NewsType()
        {
            this.A_News = new HashSet<A_News>();
            this.A_NewsType1 = new HashSet<A_NewsType>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Rank { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> Type { get; set; }
    
        public virtual ICollection<A_News> A_News { get; set; }
        public virtual ICollection<A_NewsType> A_NewsType1 { get; set; }
        public virtual A_NewsType A_NewsType2 { get; set; }
    }
}
