//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_News
    {
        public A_News()
        {
            this.A_News_File = new HashSet<A_News_File>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string ConvertPic { get; set; }
        public string KeyWord { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> IsTop { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<int> HitTimes { get; set; }
        public string StrContent { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
        public Nullable<bool> State { get; set; }
        public Nullable<int> CheckedStatus { get; set; }
        public Nullable<int> UploadAuthorId { get; set; }
        public Nullable<int> EidtAuthorId { get; set; }
        public Nullable<int> CheckedUserId { get; set; }
        public string UploadName { get; set; }
        public string EidtName { get; set; }
        public Nullable<int> AreaId { get; set; }
        public Nullable<decimal> SalePrices { get; set; }
        public Nullable<int> SaleCount { get; set; }
    
        public virtual A_NewsType A_NewsType { get; set; }
        public virtual ICollection<A_News_File> A_News_File { get; set; }
        public virtual AreaType AreaType { get; set; }
    }
}
