//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_News_File
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> NewsId { get; set; }
        public string PublishUrl { get; set; }
        public string ThumbnailsUrl { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual A_News A_News { get; set; }
    }
}
