//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_User
    {
        public A_User()
        {
            this.A_News = new HashSet<A_News>();
            this.A_News1 = new HashSet<A_News>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string Telphone { get; set; }
        public System.DateTime CreateTime { get; set; }
        public bool State { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public Nullable<System.DateTime> LastTimes { get; set; }
    
        public virtual ICollection<A_News> A_News { get; set; }
        public virtual ICollection<A_News> A_News1 { get; set; }
    }
}
