//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMessage
    {
        public System.Guid Id { get; set; }
        public string StrContent { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> Checked { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> State { get; set; }
    }
}
