//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfo
    {
        public MemberInfo()
        {
            this.OrderInfo = new HashSet<OrderInfo>();
        }
    
        public System.Guid Id { get; set; }
        public string userName { get; set; }
        public string RealName { get; set; }
        public string Telphone { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> LastLoginTime { get; set; }
        public Nullable<int> LoginTimes { get; set; }
        public string Password { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<int> AddStock { get; set; }
        public Nullable<int> Gold { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> IndustryId { get; set; }
        public Nullable<int> AreaId { get; set; }
        public string MemberNumber { get; set; }
        public string RequestNumber_1 { get; set; }
        public string RequestNumber_2 { get; set; }
        public string OpenId { get; set; }
        public Nullable<int> ZStock { get; set; }
        public Nullable<bool> State { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
    }
}
