//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_City
    {
        public S_City()
        {
            this.S_Area = new HashSet<S_Area>();
        }
    
        public int autoId { get; set; }
        public string name { get; set; }
        public string zipCode { get; set; }
        public Nullable<int> provinceId { get; set; }
    
        public virtual ICollection<S_Area> S_Area { get; set; }
        public virtual S_Province S_Province { get; set; }
    }
}
