//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Province
    {
        public S_Province()
        {
            this.S_City = new HashSet<S_City>();
        }
    
        public int autoId { get; set; }
        public string name { get; set; }
        public Nullable<int> Price { get; set; }
    
        public virtual ICollection<S_City> S_City { get; set; }
    }
}
