//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale_Contract_Header
    {
        public Sale_Contract_Header()
        {
            this.Sale_Contract_Detail = new HashSet<Sale_Contract_Detail>();
            this.Sale_Finance_FR = new HashSet<Sale_Finance_FR>();
        }
    
        public int Id { get; set; }
        public string SN { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string delivery_channel { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> AmountRecommend { get; set; }
        public string FreightCarrier { get; set; }
        public Nullable<decimal> Prepay { get; set; }
        public Nullable<bool> MeasureFlag { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> SaleUserId { get; set; }
        public string SaleUserName { get; set; }
        public Nullable<int> SaleDepartmentId { get; set; }
        public string SaleDepartment { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CheckedUserId { get; set; }
        public string CheckedUserName { get; set; }
        public Nullable<System.DateTime> CheckedTime { get; set; }
        public Nullable<System.DateTime> HTDate { get; set; }
        public Nullable<int> FRFlag { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<bool> DeleteFlag { get; set; }
        public Nullable<bool> CWCheckStatus { get; set; }
        public string CWCheckName { get; set; }
        public Nullable<int> CWCheckId { get; set; }
        public Nullable<System.DateTime> CWCheckTime { get; set; }
    
        public virtual ICollection<Sale_Contract_Detail> Sale_Contract_Detail { get; set; }
        public virtual Sale_Customers Sale_Customers { get; set; }
        public virtual ICollection<Sale_Finance_FR> Sale_Finance_FR { get; set; }
    }
}
