//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WX_Order_Commission_Logs
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> MemberId { get; set; }
        public Nullable<decimal> RequstPay { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string MemberName { get; set; }
        public string OrderNum { get; set; }
    }
}
