//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class WXReturnInfo
    {
        public System.Guid Id { get; set; }
        public string out_trade_no { get; set; }
        public string transaction_id { get; set; }
        public string openid { get; set; }
        public string trade_type { get; set; }
        public string bank_type { get; set; }
        public string total_fee { get; set; }
        public string fee_type { get; set; }
        public string time_end { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string is_subscribe { get; set; }
    }
}
