//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XiangNingSaleEntities : DbContext
    {
        public XiangNingSaleEntities()
            : base("name=XiangNingSaleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Sale_Customers> Sale_Customers { get; set; }
        public DbSet<WorkLogs> WorkLogs { get; set; }
        public DbSet<Sale_Contract_Detail> Sale_Contract_Detail { get; set; }
        public DbSet<Sale_Contract_Header> Sale_Contract_Header { get; set; }
        public DbSet<Purchase_Order> Purchase_Order { get; set; }
        public DbSet<Web_Customers> Web_Customers { get; set; }
        public DbSet<Sale_Finance_FR> Sale_Finance_FR { get; set; }
        public DbSet<Sale_Finance_FR_Logs> Sale_Finance_FR_Logs { get; set; }
    }
}
